### ISSUE TITLE
Escolher mais de um idioma.

### ISSUE THREAD

**Issue by tiagobbraga** [Godoy/open-help#7]
Nem sempre vou querer em português minhas ajudas e está muito restrito escolher qual idioma.

Não seria melhor colocar uma opção qualquer idioma ou nem mesmo escolher isso?

**Comment by Godoy** [comment]
Entendi seu raciocínio, mas não é questão de limitar a ajuda. Talvez um label melhor no momento do cadastro ajude melhor nesse entendimento.

A ideia do filtro veio conversando com uma galera que disse que queria ajudar em projetos open-source, mas se sentiria mais à vontade ajudando repositórios em português. Tendo isso no filtro, facilita essas pessoas a encontrarem um projeto no idioma desejado e que queiram ajudar.

No fim todo repositório tem um idioma default em que os commits são feitos. No Open Help, por exemplo, optei por colocar tudo em inglês - commits, issues, readme, etc. Esse campo "idioma" se refere a esse idioma default.

**Comment by tiagobbraga** [comment]
Como foi a primeira vez que vinculei meu projeto, fiquei sem saber o que colocar. Vou me acostumar 👍

**Comment by Godoy** [comment]
Mas é uma boa questão! Se você pensou dessa forma, com certeza vai ter mais questionamento sobre o uso do "idioma".
No seu https://github.com/tiagobsbraga/TBPagarME por exemplo, os commits e readme estão em inglês, acho que ficaria estranho alguém enviar pull requests com commits em Português, por exemplo. Mas se pra você, como dono do repositório, tanto faz.. acho que faz total sentido deixar a opção de "Qualquer idioma" ao cadastrar o repositório no Open Help

**Comment by tiagobbraga** [comment]
Ai você falou... 👍
